BEGIN; 

-- Delete tables if they exists
DROP TABLE IF EXISTS 
    "session",
    "best_performance",
    "user_has_sport",
    "sport",
    "category",
    "user";

-- Create user table
CREATE TABLE "user" (
    "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "email" text NOT NULL UNIQUE,
    "password" text NOT NULL,
    "firstname" text NOT NULL,
    "lastname" text NOT NULL,
    "birth_date" date,
    "city" text,
    "country" varchar(50),
    "gender" text NOT NULL,
    "weight" integer,
    "height" integer,
    "is_shared" boolean,
    "profile_picture" text,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz
);

-- Create category table
CREATE TABLE "category" (
    "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" text NOT NULL UNIQUE,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz
);

-- Create sport table
CREATE TABLE "sport" (
    "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" text NOT NULL UNIQUE,
    "unit" text NOT NULL,
    "category_id" integer NOT NULL REFERENCES "category"("id") ON DELETE CASCADE,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz
);

-- Create user_has_sport table
CREATE TABLE "user_has_sport" (
    "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" integer NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
    "sport_id" integer NOT NULL REFERENCES "sport"("id") ON DELETE CASCADE,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz,
    UNIQUE ("user_id", "sport_id")
);

-- Create best_performance table
CREATE TABLE "best_performance" (
    "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "best_score" integer NOT NULL,
    "date" date NOT NULL,
    "user_id" integer NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
    "sport_id" integer NOT NULL REFERENCES "sport"("id") ON DELETE CASCADE,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz,
    UNIQUE ("user_id", "sport_id")
);

-- Create session_table
CREATE TABLE "session" (
    "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "date" date NOT NULL,
    "description" VARCHAR(500),
    "score" integer DEFAULT 0,
    "user_id" integer NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
    "sport_id" integer NOT NULL REFERENCES "sport"("id") ON DELETE CASCADE,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz
);

COMMIT;